// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI4pHjs9qtAQQM_lPHFSKKdNTBiTY5oG0',
    appId: '1:643528071532:web:c9569fd23705f73f1c7b49',
    messagingSenderId: '643528071532',
    projectId: 'flutter-recipe-db',
    authDomain: 'flutter-recipe-db.firebaseapp.com',
    storageBucket: 'flutter-recipe-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0TkMxKVEBCqo33MmiatL5LG2ndpUUFIE',
    appId: '1:643528071532:android:ce34b563d2f5fd3b1c7b49',
    messagingSenderId: '643528071532',
    projectId: 'flutter-recipe-db',
    storageBucket: 'flutter-recipe-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLxPOS62g6Xy72YYi8V6-soDtVxSz6gY',
    appId: '1:643528071532:ios:c82c1868aef49ccb1c7b49',
    messagingSenderId: '643528071532',
    projectId: 'flutter-recipe-db',
    storageBucket: 'flutter-recipe-db.appspot.com',
    iosBundleId: 'com.example.flutterRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLxPOS62g6Xy72YYi8V6-soDtVxSz6gY',
    appId: '1:643528071532:ios:196ea1624e38fbb61c7b49',
    messagingSenderId: '643528071532',
    projectId: 'flutter-recipe-db',
    storageBucket: 'flutter-recipe-db.appspot.com',
    iosBundleId: 'com.example.flutterRecipe.RunnerTests',
  );
}
